name: "Publish"

on: workflow_dispatch
      
jobs:
  build:
    name: Build and Test
    uses: ./.github/workflows/_build.yaml

  publish:
    needs: build
    environment:
      name: production
      url: https://marketplace.visualstudio.com/items?itemName=TimHeuer.EncryptIt
    name: Publish
    runs-on: windows-2022
    permissions:
      contents: write

    env:
        VERSION: ${{ needs.build.outputs.version }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download Package artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.event.repository.name }}.vsix
    
    - name: Upload to VsixGallery
      uses: timheuer/openvsixpublish@v1
      with:
        vsix-file: ${{ github.event.repository.name }}.vsix

    - name: Publish extension to Marketplace
      #if: ${{ contains(github.event.head_commit.message, '[release]') }}
      uses: cezarypiatek/VsixPublisherAction@1.0
      with:
        extension-file: '${{ github.event.repository.name }}.vsix'
        publish-manifest-file: 'vs-publish.json'
        personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}

    - name: Tag and Release
      id: tag_release
      uses: softprops/action-gh-release@v1
      with:
        body: Release ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        generate_release_notes: true
        files: |
          **/*.vsix
    